


#define DAPPSERVICEX_CONTRACT_TEST1 "dappservicex"_n

#define DAPPSERVICESA_CONTRACT "dappservices"_n

#ifdef LIQUIDX

#define DAPPSERVICES_CONTRACT DAPPSERVICEX_CONTRACT_TEST1

#else

#define DAPPSERVICES_CONTRACT DAPPSERVICESA_CONTRACT

#endif